delimiter $$

CREATE TABLE `COSTCONFIGURATION` (
  `SOURCEID` int(11) NOT NULL,
  `DESTINATIONID` int(11) NOT NULL,
  `COST` decimal(5,2) NOT NULL,
  PRIMARY KEY (`SOURCEID`,`DESTINATIONID`),
  KEY `SOURCEID_idx` (`SOURCEID`),
  KEY `DESTINATIONID_idx` (`DESTINATIONID`),
  CONSTRAINT `destinationid` FOREIGN KEY (`DESTINATIONID`) REFERENCES `DESTINATION` (`DESTINATIONID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sourceid` FOREIGN KEY (`SOURCEID`) REFERENCES `SOURCE` (`sourceid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$



delimiter $$

CREATE TABLE `DESTINATION` (
  `DESTINATIONID` int(11) NOT NULL AUTO_INCREMENT,
  `DESTINATIONNAME` varchar(45) NOT NULL,
  PRIMARY KEY (`DESTINATIONID`),
  UNIQUE KEY `DESTINATIONNAME_UNIQUE` (`DESTINATIONNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1$$



delimiter $$

CREATE TABLE `SOURCE` (
  `sourceid` int(11) NOT NULL AUTO_INCREMENT,
  `sourcename` varchar(45) NOT NULL,
  PRIMARY KEY (`sourceid`),
  UNIQUE KEY `sourcename_UNIQUE` (`sourcename`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1$$



delimiter $$

CREATE TABLE `USER` (
  `USERNAME` varchar(20) NOT NULL,
  `FIRSTNAME` varchar(45) NOT NULL,
  `LASTNAME` varchar(25) NOT NULL,
  `USERTYPE` enum('ADMIN','CUSTOMER','COMPANY') NOT NULL,
  `GENDER` varchar(7) NOT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `MOBILE` varchar(45) DEFAULT NULL,
  `DOB` datetime DEFAULT NULL,
  `PASSWORD` varchar(25) NOT NULL,
  `UPDATEDDATE` datetime NOT NULL,
  PRIMARY KEY (`USERNAME`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

